# Generated by Django 4.1.7 on 2023-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="face_dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=64)),
                ("secondname", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.FileField(upload_to="dataset/")),
            ],
        ),
        migrations.CreateModel(
            name="Unknown_dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capture_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="dataset/")),
                ("title", models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="unrecognized",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.IntegerField()),
                ("cap_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
