# Generated by Django 4.1.7 on 2023-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_camera", "0002_unrecognized_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unrecognized",
            name="status",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
